# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20161215_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='rating',
        ),
    ]
